apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: data-content
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk-basic
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
status: {}
